### ISSUE TITLE
Temperature quickly goes down when on a boat in winter

### ISSUE THREAD

**Issue by Leiriad** [wendall911/Homeostatic#61] opened 2024-08-15 16:21 UTC
I play in 1.20.1, on Homeostatic 2.9.8.0. I don't know if it's a normal feature or a bug, but temperature decreases quickly when you are on a boat in winter even if you have insulation. Do you need waterproof clothes too?

Also, a config file to allow players/server owners to manage the difficulty by attoning or increasing the different effects of heat, cold and wetness would be great.

**Comment by wendall911** [comment] 2024-08-15 17:47
If you aren't getting wet, then no, there is no difference being in the boat. It will largely depend on the water you are in. Rivers are warmest, deep cold ocean is coldest. Waterproofing probably won't help, it is just cold, so you need to stop and get warm, probably a campfire.

This mod is constructed differently than other mods. Pretty much every aspect can be adjusted through datapacks. Doing this in configs isn't how things are adjusted now. https://github.com/wendall911/Homeostatic/wiki/Data-Pack-Customizations So heat/cold are not magic, but attempt to be a simulation. It has already been super tamed down to have it be playable. For more difficulty, there are other mods that can be added, like Primal Winter. Removing seasons would also have the affect of making it easier. Maybe adding a config to set to a specific season and ignore seasons would be an option? Changing, or even allowing configuration of how temperature calculations happen is almost impossible to expose to a config, as it is almost entirely based on some actual weather math (see: https://github.com/wendall911/Homeostatic/wiki/Temperature-Calculations).

A possibility for you is to add a slight warming effect for boats by giving it a slight radiation effect if you don't want to get cold running around outside in the winter.

For modpacks, I recommend using https://www.curseforge.com/minecraft/mc-mods/drp-global-datapack to manage datapack changes. I know in the past, like 1.16 and before were all configs, but anything modern will be adjustable mostly through datapacks. Configs are for things that aren't easy or possible to datapack.

I'm not sure how to respond to this request, as it appears as though the mod is working as intended, however, one thing we've been considering though is adding some type of warming potion or drink. This would allow for exploring cold areas when insulation isn't sufficient. I'm not sure if that should be a potion (which are not an easy option) or maybe something stimulating? I'd be open to any ideas you might have though.

**Comment by Leiriad** [comment] 2024-08-16 14:08
If you want to make things realistic, I think the player should get cold with insulated clothes only if they're not moving, as our body emits radiation when moving. So when walking, running and rowing the body temperature shouldn't do down unless the food bar is low. 

On the other hand, if you work on a compatibility with Vampirism, I think the basic vampire body temperature should be low, and shouldn't go up while moving but should go up after drinking blood from an animal (but not from a bottle).

**Comment by Leiriad** [comment] 2024-08-17 14:53
I tried to make a data pack to make the boat emit radiation but it doesn't work. My pack is in "datapacks", it is called InventoriumCompatibility, and has this structure:
- data
-- minecraft
--- environment
---- block_radiation
----- oak_boat.json
- pack.mcmeta


My pack.mcmeta is like this:
{
    "pack": {
      "pack_format": 15,
      "description": "Tutorial Data Pack"
    }
}

And my oak_boat.json file is like this:
{
	  "block": "minecraft:oak_boat",
	  "max_radiation": 500.0
}

It's the first time I do such a thing, where am I doing something wrong?

**Comment by wendall911** [comment] 2024-08-17 16:50
Let me do some testing and I'll see what you can do.

**Comment by wendall911** [comment] 2024-08-19 16:30
Actually, this is a bug. You are considered partially submerged when in a boat. I'll push out a fix for this, then move on to working out some warming mechanism when traveling in cold environments.

**Closed as completed** 2024-08-19 18:37 UTC

**Comment by wendall911** [comment] 2024-08-19 18:39
I've updated all versions. Give this a shot. Sorry it took so long to test and fix. I didn't see the problem initially.
