### ISSUE TITLE
Enhancement Change position of temp meter..

### ISSUE THREAD

**Issue by TheeMrCheeky** [wendall911/Homeostatic#6] opened 2022-10-18 03:26 UTC
Pretty straight forward, Be able to change position of temp meter... (also maybe make it so running/jumping slightly increases temp) that would be pretty realistic as well
![image](https://user-images.githubusercontent.com/96976998/196328696-31b22e72-7510-4bc4-bcc5-1b629a99b805.png)

**Comment by wendall911** [comment] 2022-10-18 17:00
Given all the hud clutter you have, I'm uncertain where another position is available. I may do something similar to Tough As Nails and place something between the health and hunger bars. I've had a similar suggestion from others. Thoughts?

**Comment by TheeMrCheeky** [comment] 2022-10-18 17:23
Well that clutter is from a good useful mod called inventory hud :D so pretty sure others would ask the same thing eventually. I was just saying if it was possible to move the temperature bar around the screen that would be cool, You could check out survives implementations of it as well where the hot bar itself will fade from blue for cold and red/orange for hot. Sure there is plenty of ways to make it. That little thermometer is fine just being able to move it around in config some how would make a world of difference for customization

**Comment by wendall911** [comment] 2022-10-18 18:10
Ok, great. Thanks for the feedback. I'll work on this and see what I can come up with.

**Comment by Tellik** [comment] 2022-11-01 13:53
To add to this discussion,

I would also like to be able to configure the visual overlay elements, at the very least to be able to reposition them, at the most to be able to configure them through a HUD mod, such as RPG-HUD or Spiffy HUD. 

Here's a better example of an overlay repositioned with the mod's default elements where they are.

![image](https://user-images.githubusercontent.com/6219444/199249446-1301b0aa-df91-4523-bd09-215fd44c1ebf.png)

**Comment by wendall911** [comment] 2022-11-01 15:01
Still working on this. I've worked through some good (and bad) ideas for this. I will take a look at the alternate HUD mods as well and add support. Once I have this work complete, I plan to have it highly configurable so it can fit multiple scenarios if needed.

**Comment by wendall911** [comment] 2022-11-03 21:14
@Tellik Both of those HUD mods are still stuck on 1.18.2 & Spiffy HUD has been discontinued. I don't mind backporting to 1.18.2, but the issue is that I really only want to support actively maintained mods right now. I'll see what I can do for being able to move the water bar. I already have a solution for the temperature stuff.

The issue with breaking the minecraft HUD is that a lot of things are dependent on dynamic HUD elements in vanilla. So, for example, if I allow for static positioning of the water bar, it breaks when riding a horse or under water, as there are additional bars rendered.

**Comment by Tellik** [comment] 2022-11-03 23:18
Yeah, I can understand a lot of that. I would like to say that RPG-HUD would move to 1.19+, since it's still in active developement. Also, it is a shame that Spiffy HUD was discontinued. Ultimately, being able to move the temperature and thirst UI display elements would be the bare minimum.

What I did end up doing for now is switching to Classic Bars.

![image](https://user-images.githubusercontent.com/6219444/199838810-12afe65c-7c73-4dee-95d6-1d1b2dee1d31.png)

I imagine I would need to talk to the devs for Classic Bars to provide a compatbility layer for Homeostatic, but one nice thing is that they provide some of the display changes I'm looking for. 

You can kind of see where some of the issues are though even with this, with some of the overlap with the temperature. Also one thing I noticed is that the thirst display disappears when in a boat. I don't know if that's intended. Though it also doesn't come back when I exit the boat or save/quit/load.

Switching from static placed, to being able to be user placed would solve a lot of the issues that I'm running into, even between using Classic Bars or a full HUD replacement like RPG-HUD.

**Comment by wendall911** [comment] 2022-11-04 14:49
This is great feedback. I will play around with classic bars and see what can be done. I should have something released for this soon as a beta to get some feedback before moving forward with the changes.

**Comment by wendall911** [comment] 2022-11-04 23:49
Ok, latest release has quite a few HUD changes and a book. The temperature HUD is different (but can still set to use the old one if desired). I will leave this open for now, as I want to add full support for Classic Bars, but have not done so yet.

**Comment by Tellik** [comment] 2022-11-06 00:02
I like a bit of the changes and ideas you put in there. (Also like how you can tweak some of the positions of everything.)

One recomendation I would have is to remove the degree symbol from the numerical display. (I feel like I'm nitpicking at this point) 
![image](https://user-images.githubusercontent.com/6219444/200147549-01b02d48-fcdb-4842-9bd6-5812da402b2b.png)

Or, maybe extend the black box a little bit so it fully can provide a background for the temperature. It sometimes, is a little difficult to see against similar color backgrounds (like this birch tree)

![image](https://user-images.githubusercontent.com/6219444/200147599-e6d87b50-33b5-41b8-88aa-d441276d4594.png)

At the very least, this definitely does everything I need it to, so that's amazing and thank you. I'll continue playing around with it a little more and see if I find out any issues with anything, but so far looks great.

**Comment by wendall911** [comment] 2022-11-11 02:45
Closing this issue now as resolved. I added a separate issue for adding Classic Bars support. Latest release adds small tweaks that allow for hiding degree symbol and couple other features. See #9

**Closed as completed by wendall911** 2022-11-11 02:45 UTC
